service:
  name: krankenhausnavi
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    excludeFiles: src/**/*.test.js

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  timeout: 6
  versionFunctions: false
  stage: dev
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    # AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    RDS_HOSTNAME: ${file(./config/database.${self:provider.stage}.json):hostname}
    RDS_USERNAME: ${file(./config/database.${self:provider.stage}.json):username}
    RDS_PASSWORD: ${file(./config/database.${self:provider.stage}.json):password}
    RDS_PORT: ${file(./config/database.${self:provider.stage}.json):port}
    RDS_DATABASE: ${file(./config/database.${self:provider.stage}.json):database}

functions:
  find-institutions:
    handler: src/find-institutions.handler
    events:
      - http:
          method: get
          path: institutions
  get-institutions:
    handler: src/get-institutions.handler
    events:
      - http:
          method: get
          path: institutions/{institutionId}
          request:
            # Add validators in gateway later: https://serverless.com/framework/docs/providers/aws/events/apigateway#request-schema-validators
            parameters:
              paths:
                institutionId: true
